name = "llmgleam"
version = "0.0.4"

description = "Gleam bindings for various LLMs"
licences = ["MIT"]
repository = { type = "github", user = "Endi1", repo = "llmgleam" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.1.1 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_hackney = ">= 1.3.2 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
